### PR TITLE
Migrate dependencies to nugets

### PR DESCRIPTION
**Pull request by gmrukwa**
I've removed all of the projects that are now enclosed into NuGet packages.

### CODE REVIEW

**Comment by gmrukwa** [comment]
[Extract common .NET modules to NuGets](https://trello.com/c/5SSNPeaF/333-extract-common-net-modules-to-nugets)

**Review by Daroslaw — APPROVED** [review]
It's a shame that removal of unneccessary projects isn't in some previous, separate PR.

**Comment by gmrukwa** [comment]
These projects are the dependencies replaced by NuGets. They could not be replaced earlier. Before I've pruned everything that could be pruned at that moment.

**Review by mg6 — APPROVED** [review]

**Comment by gmrukwa** [comment]
[Migrate DiviK client to platform NuGet](https://trello.com/c/pmclfZV0/335-migrate-divik-client-to-platform-nuget)

**Pull request merged**
